apiVersion: v1
kind: Secret
metadata:
  name: ai-pipeline-secrets
type: Opaque
data:
  # Base64 encoded values
  db-user: cGlwZWxpbmU=  # pipeline
  db-password: cGFzc3dvcmQ=  # password
  database-url: cG9zdGdyZXNxbDovL3BpcGVsaW5lOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZTo1NDMyL3BpcGVsaW5lX2Ri
  redis-url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA==
  api-secret-key: c3VwZXItc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbi11c2U=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-pipeline-config
data:
  deployment-mode: "production"
  log-level: "info"
  max-workers: "4"
  rate-limit: "100"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
